### ISSUE TITLE
Немного поменялся алгоритм

### ISSUE THREAD

**Issue by snhplayer** [mikhailnov/getcourse-video-downloader#15]
Теперь m3u8 кодируется base64

**Comment by mikhailnov** [comment]
Можно пример?

**Comment by snhplayer** [comment]
Все нормально, файл скачивается как надо.
Я переписал ваш скрипт на python и добавил автоконверт в mp4, я могу залить этот скрипт к себе на гитхаб? Или лучше запулить сюда

**Comment by mikhailnov** [comment]
То есть кодирования в base64 нет? 

На python лучше к себе отдельным проектом, а я в README.md могу указать ссылку, как на альтернативный вариант.

**Comment by snhplayer** [comment]
Кодирования нет

Хорошо, пару фич допилю с readme и скину ссылку

**Comment by snhplayer** [comment]
Доделал
https://github.com/snhplayer/GetCoursePythonDownloader

**Comment by mikhailnov** [comment]
Добавил ссылку на него в README.
Но по коду не очень понял, зачем запускать конвертирование в mp4 несколько раз — почему оно может не удастся?
`ffmpeg -c copy` хорошая идея.

**Comment by snhplayer** [comment]
Спасибо!
У меня бывало, что конвертирование не удавалось. Причину найти не смог, поэтому закостылил, надеюсь у других будет работать лучше.
