### ISSUE TITLE
уточнить инструкцию

### ISSUE THREAD

**Issue by rinxster** [mikhailnov/getcourse-video-downloader#7]
Так полагаю, если в отладочной информации содержится в названии *.m3u файла есть есть цифра(1080.m3u8 или 480.m3u), то это качество в котором можно скачать файл. Таким образом, можно выбрать в каком качестве вам скачать.
Может быть это стоить протестировать и добавить в инструкцию?

**Comment by mikhailnov** [comment]
В инструкции написано: "Выберите нужное разрешение видео в настройках видеоплеера GetCourse". А просто замена цифр в ссылке не поможет.
