### ISSUE TITLE
Обновился алгоритм генерации ссылок для видео

### ISSUE THREAD

**Issue by alx8437** [mikhailnov/getcourse-video-downloader#8]
Не работают предыдущие способы. Обычно я мспользую HLS Downloader  расширение для загрузки, но если больше одного видео на странице - не работает.

**Comment by mikhailnov** [comment]
Да вроде бы по способу 1 без изменений, m3u8 отдается, что изменилось?

**Comment by nikiska77** [comment]
перестал работать ваш способ буквально в течение последнего месяца. в марте еще скачивала, а вчера уже выдает ошибку - доступ запрещен: 
touch: video.ts: Permission denied

**Comment by mikhailnov** [comment]
Это у вас на компе прав на запись не хватает
