### ISSUE TITLE
Изменился алгоритм

### ISSUE THREAD

**Issue by nikdj0ker** [mikhailnov/getcourse-video-downloader#9]
Изменился алгоритм. Нет ни m3u ни data-master

**Comment by mikhailnov** [comment]
m3u8 на месте, по крайней мере у того видео, где он был раньше.

![image](https://github.com/mikhailnov/getcourse-video-downloader/assets/15802528/3815618a-5c7e-423b-8163-ccff32d2fd45)

**Comment by DrMashine** [comment]
Звук теперь отдельно лежит, и видео кусками, а не целым файлом.
![image](https://github.com/mikhailnov/getcourse-video-downloader/assets/45767800/b2170c7b-6060-4e29-b3c3-3dd12c1ca3ec)

**Comment by mikhailnov** [comment]
Можете прислать на `m@mikhailnov.ru` доступ к этому видео?

**Comment by visota2000** [comment]
Добрый день. Подскажите плиз, как от этих ошибок избавиться?
<img width="946" alt="Снимок экрана 2023-11-29 132442" src="https://github.com/mikhailnov/getcourse-video-downloader/assets/87056012/5e051a5f-34f8-4fb0-ac5c-4c83e136fe4a">

**Comment by nikiska77** [comment]
<img width="858" alt="Screenshot 2023-12-02 at 11 22 04" src="https://github.com/mikhailnov/getcourse-video-downloader/assets/86112104/6d64e5f5-011c-43c7-84d7-1842056602e3">
у меня тоже выдается только echo при запуске скрипта, и больше ничего не происходит. приходится прерывать выполнение ctrl+C. причем странно, что первое видео скачалось, а потом я перегрузила комп и перестало работать. не понимаю в чем проблема

**Comment by nikiska77** [comment]
Another update. Run it using set - x and here are some details that might help: 
<img width="570" alt="Screenshot 2023-12-03 at 13 34 42" src="https://github.com/mikhailnov/getcourse-video-downloader/assets/86112104/f9400493-d935-4315-957a-c17f99c27dc3">

**Comment by nikiska77** [comment]
<img width="573" alt="Screenshot 2023-12-03 at 13 36 46" src="https://github.com/mikhailnov/getcourse-video-downloader/assets/86112104/e762f692-35f8-45fd-b6af-607e61b93205">

и в конце надо завершать CTRL +C иначе не выходит из режима ожидания

**Comment by artk42** [comment]
да, есть альтернативный алго, нарубленный как колбаса, по отдельности куски открывать не получается

<img width="443" alt="Screenshot 2023-12-24 at 16 22 05" src="https://github.com/mikhailnov/getcourse-video-downloader/assets/8707649/3d8ed2e1-8b40-4426-8900-591f1a18bfce">

**Comment by mikhailnov** [comment]
@artk42 можете прислать доступ к такому видео на почту m@mikhailnov.ru или в телеграм t.me/mikhailnov? На глаз по скриншоту снаряд выглядит легким, но, возможно, без перекодирования фрагментов видео не обойдемся.

**Comment by artk42** [comment]
![Untitled1](https://github.com/mikhailnov/getcourse-video-downloader/assets/8707649/41da99cb-73f4-413d-aac7-8eafe3d12825)
Вот еще один, похоже они системно поменяли подход, здесь .ts нарублены по полмегабайта

**Comment by Funk2256** [comment]
Доброго, подтверждаю алгоритм изменился, вашим скриптом выдернуть не получилось

`bash /tmp/getcourse-video-downloader.sh "https://player02.getcourse.ru/sign-player/\?json\=eyJ2aWRlb19oYXNoIjoiNDE4YmY3YWZhYzYxNTg2ODc0ZWQ1ZTUyYzgzMTliYTAiLCJ1c2VyX2lkIjoyOTYzNTkxOTEsInN1Yl9sb2dpbl91c2VyX2lkIjpudWxsLCJsZXNzb25faWQiOjI3NzU5ODc0NiwiaXAiOiIxMDkuMTA3LjE3My4yMDYiLCJnY19ob3N0Ijoic3Rhcm9zaGNodWthbGVuYS5nZXRjb3Vyc2UucnUiLCJ0aW1lIjoxNzA5MjE2NDYxLCJwYXlsb2FkIjoidV8yOTYzNTkxOTEiLCJ1aV9sYW5ndWFnZSI6InJ1IiwiaXNfaGF2ZV9jdXN0b21fc3R5bGUiOnRydWV9\&s\=4195a33951dd9b3de10546b980cd7b80\&vh-static-feature\=zigzag" "2.ts"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    39    0    39    0     0     56      0 --:--:-- --:--:-- --:--:--    56
grep: предупреждение: лишняя \ перед /
grep: предупреждение: лишняя \ перед /
В содержимом заданной ссылки нет прямых ссылок на файлы *.ts (первый вариант),
также последняя строка в ней не содержит ссылки на другой плей-лист (второй вариант).
Либо указана неправильная ссылка, либо GetCourse изменил алгоритмы.
Если уверены, что дело в изменившихся алгоритмах GetCourse, опишите проблему здесь:
https://github.com/mikhailnov/getcourse-video-downloader/issues (на русском).`

![Uploading Снимок экрана_2024-02-29_22-23-59.png…]()


https://player02.getcourse.ru/player/1a3b37f2dd1248af7de811d6a88c7e34/b1e959bf101e0a5705be205a95d2a400/media/480.m3u8?sid=&user-cdn=gcore&version=10:2:1:0:gcore&user-id=296359191&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyLWlkIjoyOTYzNTkxOTF9.UzRfoYeGi7c83lC9uWG1INqEiXlW7-h1eJtGajb5TuI

**Comment by Funk2256** [comment]
https://github.com/puemos/hls-downloader - Этим смог выдернуть все нужные видосы.

**Comment by artk42** [comment]
> https://github.com/puemos/hls-downloader - Этим смог выдернуть все нужные видосы.

Да, хорошая штука, кое где срабатывает, но далеко не везде увы. Я перебрал еще 4 подобных экстеншенов, ни один не подцепил (

**Comment by sayblessme** [comment]
Не знаю Геткурс изменил алгоритмы или нет, но видео раздроблено на много кусков, расширения их находят, но они скачиваются только в формате .bin. Через терминал также не получилось :(

**Comment by dyodik** [comment]
Поменялся в принципе плеер у многих курсов, который не цепляет потоки никаким способом

**Comment by vetka-nn** [comment]
Добрый день! Геткурс действительно изменил алгоритм, по-видимому, в течение последней недели. Теперь ифрейм с видеофайлом не содержит в своём коде ссылку на m3u, параметр data-master url пустой. Например, HLS downloader и JDownloader2 в прямой ссылке на ифрейм ничего не находят.

Но тем не менее, ссылку добыть можно – она лежит в ифрейме же, но в джаваскрипте. И по этой ссылке уже нормально скачивает файл и HLS downloader, и ваш скрипт.

<img width="712" alt="Снимок экрана 2024-07-07 в 01 58 03" src="https://github.com/mikhailnov/getcourse-video-downloader/assets/48964706/b0bcd1c2-738c-4e75-81b1-8ee23e0ec35b">

**Comment by tinky23** [comment]
> Добрый день! Геткурс действительно изменил алгоритм, по-видимому, в течение последней недели. Теперь ифрейм с видеофайлом не содержит в своём коде ссылку на m3u, параметр data-master url пустой. Например, HLS downloader и JDownloader2 в прямой ссылке на ифрейм ничего не находят.
> 
> Но тем не менее, ссылку добыть можно – она лежит в ифрейме же, но в джаваскрипте. И по этой ссылке уже нормально скачивает файл и HLS downloader, и ваш скрипт.
> 
> <img alt="Снимок экрана 2024-07-07 в 01 58 03" width="712" src="https://private-user-images.githubusercontent.com/48964706/346302575-b0bcd1c2-738c-4e75-81b1-8ee23e0ec35b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzk1NzEsIm5iZiI6MTcyMDMzOTI3MSwicGF0aCI6Ii80ODk2NDcwNi8zNDYzMDI1NzUtYjBiY2QxYzItNzM4Yy00ZTc1LTgxYjEtOGVlMjNlMGVjMzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA4MDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZWJlMWU4NWM2MzRkYTUyMTBlMDY4MmQ5NzNlOTJkYzFiN2U1NGQ4OGI0NjhkZmFjNmE0NzVkYTQyNjA0NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bUsrKYsr8kNUpuD9Y8_6MGHjtEpoAJ4trN1TRCkdUJw">

Добрый день! Подскажите пожалуйста, а что дальше делать с этим скриптом? Как вытащить ссылку для HLS?

**Comment by vetka-nn** [comment]
> 
> Добрый день! Подскажите пожалуйста, а что дальше делать с этим скриптом? Как вытащить ссылку для HLS?

Добрый день! Судя по самому вопросу, вам лучше всего дождаться, пока автор этого скрипта учтёт последние изменения и обновит свой скрипт. :) 

Ссылка лежит там в открытом виде, нужно просто её скопировать и подсунуть HLS или данному скрипту.

**Comment by kirxkirx** [comment]
Сработал вот такой скрипт [download_video3_py.txt](https://github.com/user-attachments/files/16120662/download_video3_py.txt). Сохраняем HTML-страницу с уроком в файл и указываем его в качестве параметра командной строки скрипту. Для скачивания скрипт использует youtube-dl. 

Чтобы получить ссылку на видео которую надо передать youtube-dl, в коде страницы находим все блоки `iframe id=` и проходим по ссылке из поля `src=` в этом блоке (один блок iframe - одно видео). Ссылка ведёт на HTML блок в котором уже есть ссылка на само видео в элементе `masterPlaylistUrl` - надо только все обратные слэши которые эсекйпят обычные слэши в адресе убрать.

Похоже, что на гиткурсе разный алгоритм для разных курсов. Сейчас смотрю на другой курс, а там видео - просто вставка ютуба вместо кастомного плеера.

**Comment by vetka-nn** [comment]
> Похоже, что на гиткурсе разный алгоритм для разных курсов. Сейчас смотрю на другой курс, а там видео - просто вставка ютуба вместо кастомного плеера.

Это зависит от владельца аккаунта на геткурсе. Одни вставляют видео с ютуба, и тогда его добыть проще простого, другие заливают в само хранилище геткурса (сам геткурс позволяет оба варианта), и тогда уже начинаются танцы с бубном.

**Comment by mikhailnov** [comment]
Сделал поддержку *.bin: https://github.com/mikhailnov/getcourse-video-downloader/commit/0fa77f5f10dbfe63c7d1a3cc2795fd2c58beecde

Это то же самое, что ts.

**Comment by mikhailnov** [comment]
А вот колбасы из mp4 не видел, нужен пример...
